### ISSUE TITLE
Discord icon on footer.

### ISSUE THREAD

**Issue by killerclaws12** [GhostyORG/Ghosty-web#62]
Ive gotten reports when you click the icon on the footer (the discord one), it brings a invalid inv link up.

**Comment by Abir-Tx** [comment]
I think then it still uses the old or invalid link

**Comment by killerclaws12** [comment]
ill send a valid one and who ever has time, pls fix it. Im so confused when lookin at these files. Idk were everything is lmao

**Comment by killerclaws12** [comment]
https://discord.gg/ztDEQjwKbP

**Comment by Abir-Tx** [comment]
Fixed in 71b0dfc780cbfa1ed270a095291c3e982435fc46
