### ISSUE TITLE
Nav elements text color

### ISSUE THREAD

**Issue by Hero1230** [GhostyORG/Ghosty-web#68]
On a white theme the selected nav element has low contrast.
<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/42366462/203836776-64f680dc-b003-42e3-a7d7-2706cdf57896.png">

**Comment by killerclaws12** [comment]
Thanks for all your contributing btw and thanks for letting us know! We appreciate it!

**Comment by Abir-Tx** [comment]
Thanks @Hero1230. This might be caused by the new commit pushes right @killerclaws12 ?

**Comment by killerclaws12** [comment]
Yep! Due to us trying to make a xmas theme for the month December. I'll either get @Abir-Tx or @virtual-designer started on fixing it.

**Comment by Abir-Tx** [comment]
Okay adding it on my list

**Comment by killerclaws12** [comment]
Okay!
